// Alert
export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";

export const LOADING_ADMIN_START = "LOADING_ADMIN_START";
export const LOAD_ADMIN_SUCCESS = "LOAD_ADMIN_SUCCESS";
export const LOAD_ADMIN_FAIL = "LOAD_ADMIN_FAIL";

export const LOADING_ADMIN_LOGIN = "LOADING_ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const LOADING_ADMIN_REGISTER = "LOADING_ADMIN_REGISTER";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";

//users
export const LOADING_USERS_START = "LOADING_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAIL = "LOAD_USERS_FAIL";

// vouchers
export const LOADING_VOUCHERS_START = "LOADING_VOUCHERS_START";
export const LOAD_VOUCHERS_SUCCESS = "LOAD_VOUCHERS_SUCCESS";
export const LOAD_VOUCHERS_FAIL = "LOAD_VOUCHERS_FAIL";


// subscriptions
export const LOADING_SUBSCRIPTIONS_START = "LOADING_SUBSCRIPTIONS_START";
export const LOAD_SUBSCRIPTIONS_SUCCESS = "LOAD_SUBSCRIPTIONS_SUCCESS";
export const LOAD_SUBSCRIPTIONS_FAIL = "LOAD_SUBSCRIPTIONS_FAIL";
export const EDIT_SUBSCRIPTIONS_START = "EDIT_SUBSCRIPTIONS_START";
export const EDIT_SUBSCRIPTIONS_SUCCESS = "EDIT_SUBSCRIPTIONS_SUCCESS";
export const EDIT_SUBSCRIPTIONS_FAIL = "EDIT_SUBSCRIPTIONS_FAIL";


// payment
export const LOADING_PAYMENT_START = "LOADING_PAYMENT_START";
export const LOAD_PAYMENT_SUCCESS = "LOAD_PAYMENT_SUCCESS";
export const LOAD_PAYMENT_FAIL = "LOAD_PAYMENT_FAIL";
export const EDIT_PAYMENT_START = "EDIT_PAYMENT_START";
export const EDIT_PAYMENT_SUCCESS = "EDIT_PAYMENT_SUCCESS";
export const EDIT_PAYMENT_FAIL = "EDIT_PAYMENT_FAIL";


export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";